### ISSUE TITLE
tools/cc1 is an x86 binary

### ISSUE THREAD

**Issue by ecumber** [ethteck/papermario#41]
The executable tools/cc1 is an x86 binary, which means it can't run in WSL. Could an x64 binary be provided in the next commit, or the source code for building an x64 version?

**Comment by ethteck** [comment]
Hi, thanks for submitting this issue! The cc1 binary will actually run in WSL2, but you're right it doesn't run on WSL1. For various other reasons, I recommend you upgrade to WSL2, but I agree we need to address this since many people won't want to upgrade.

We'll be including the patch to gcc 2.8.1 we use as well as some build instructions soon. Also, are you a member of the [Paper Mario Modding discord](https://discord.gg/fC6yNu)? Feel free to reach out to us in the #decomp channel there, we're in very early stages and would love any new contributors.

**Comment by pixel-stuck** [comment]
Up until recently, it was an x64 binary, but given the compiler from the era isn't really designed for that environment, we had issues. I'll attempt to patch the compiler for 64-bit support, and hopefully I'll get everything. A patch will be provided as Ethan mentioned, too.

**Comment by ethteck** [comment]
@ecumber we're in the process of sorting out all our custom changes to gcc and binutils. See the following repos:
https://github.com/ethteck/gcc-papermario
https://github.com/ethteck/binutils-papermario

The binutils one still needs our patch applied, but the gcc one should work. However, building this old of a version of gcc is quite difficult on modern computers. We'll publish more instructions soon enough, but I wanted to at least give you an update.

**Comment by ethteck** [comment]
I've added PAPERMARIO.md files to the two aforementioned repos. This should help get you started with building GCC. However, there are issues with the "plain" 64-bit build, which is why we are building with `-m32`.

I'm going to close this for now since we have the more platform-friendly cc1 recently checked in and resources one can use to build their own cc1 if they desire.
